---
- name: アプリをビルドする
  ansible.builtin.command:
    argv: [/bin/bash, -lc, "{{ build_command }}"]
    chdir: "{{ app_working_dir }}"
  changed_when: true
  when:
    - inventory_hostname in groups['app']
    - build_command | length > 0
