---
# monitor_state: on | off
- name: Netdataを制御する
  ansible.builtin.systemd:
    name: "{{ netdata_service }}"
    state: "{{ 'started' if monitor_state == 'on' else 'stopped' }}"
    enabled: "{{ monitor_state == 'on' }}"
  become: true
  when: inventory_hostname in groups.get('all', [])

- name: MariaDBのスロークエリログを制御する
  ansible.builtin.command:
    argv:
      - "{{ mysql_admin_command }}"
      - >-
        --execute={% if monitor_state == 'on' %}SET GLOBAL long_query_time={{ mysql_slow_query_time }}; SET GLOBAL slow_query_log='ON';{% else %}SET GLOBAL slow_query_log='OFF';{% endif %}
  become: true
  changed_when: true
  when: inventory_hostname in groups.get('db', [])
