---
- name: アプリホストのpprofを切り替える
  hosts: app
  gather_facts: false
  pre_tasks:
    - name: pprof設定を検証する
      ansible.builtin.assert:
        that: instrument_state in ['on', 'off']
        fail_msg: "instrument_state must be on or off"

  tasks:
    - name: pprofを切り替える
      ansible.builtin.include_tasks: tasks/app/pprof.yml
