all:
  vars:
    ansible_user: isucon
  children:
    app:
      hosts:
        isucon-1:
          ansible_host: 52.195.6.219
          private_ip: 10.0.0.202
    db:
      hosts:
        isucon-2:
          ansible_host: 13.193.217.22
          private_ip: 10.0.0.121
    nginx:
      hosts:
        isucon-1:
    # 開始案内、スコア入力、統合レポートの基準にするホストを1台指定します。
    reporter:
      hosts:
        isucon-1:
